/*  2017/12/16  version 1.0
 * coding: utf-8, Tab as 4 spaces
 * 
 * Home Energy Diagnosis System Ver.6
 * scenariofix.js 
 * 
 * fix area function and data between home and office
 * fix scenario.js
 * fix logic definition
 * 
 * License: http://creativecommons.org/licenses/LGPL/2.1/
 * 
 * @author Yasufumi Suzuki, Hinodeya Institute for Ecolife co.ltd.
 * 								2016/04/12 ported to JavaScript
 * 
 * 
 */

// D6.scenario.areafix  fix area set by home/office
// called by diagnosis.js  just after create scenario
D6.scenario.areafix = function() {
	//set area and person to calculate average, heat load etc.
	D6.area.setCalcBaseParams = function(){
		D6.area.setPersonArea( D6.doc.data.i001, D6.doc.data.i021, D6.doc.data.i023);		
	};
	
	//get seasonal parameters
	D6.area.getSeasonParamCommon = function(){
		return D6.area.getSeasonParam(  D6.area.area  );
	};

	D6.scenario.defMeasures['mTOsolar'] = { mid:"1",  name:"mTOsolar",  title:"太陽光発電を設置する",  easyness:"0.5",  refCons:"consTotal",  titleShort:"太陽光発電", level:"",  figNum:"25",  lifeTime:"20",  price:"400000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"発電で余った電気は、電力会社に高く買い取ってもらうことができます。2017年度は1kWhあたり28円（東京電力、中部電力、関西電力の場合）、もしくは30円（それ以外の電力会社では高いですが、太陽光が余剰となったときに買い取りを停止する装置の設置が必要になります）。パネルを設置するだけで発電がされ、モーターなど稼働する部分がないために寿命が長く、維持管理も比較的少なくて済みます。交流に変換をする「コンディショナー」と呼ばれる装置は10年程度ごとに交換が必要になります。<br>　また、太陽光発電装置を導入すると、電気を売る様子が表示される装置が設置されます。電気をどれだけ発電できたのか、家庭でどれだけ消費したのかが表示され、機種によっては時間帯別に表示されるものもあります。販売できた金額も表示され、より多く販売するために自然と電気の使用量が減る効果も出てきます。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mTOhems'] = { mid:"2",  name:"mTOhems",  title:"HEMS装置を設置する",  easyness:"1",  refCons:"consTotal",  titleShort:"HEMS装置", level:"",  figNum:"3",  lifeTime:"20",  price:"200000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"HEMSとは、家庭で使っている電気を時間ごとに細かく把握したり、エアコンなどの家電製品を、省エネのために自動制御したりできるシステムです。電気の使い方などの特徴をチェックすると、どんなことをすれば省エネにつながるか、ポイントが見えてきます。表示されるグラフをもとに、いつ電気の消費が多いのか、何が原因なのか、考えてみてください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mTOsolarSmall'] = { mid:"3",  name:"mTOsolarSmall",  title:"ベランダに太陽光パネルを置く",  easyness:"2",  refCons:"consTotal",  titleShort:"ベランダ太陽光", level:"",  figNum:"25",  lifeTime:"10",  price:"50000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"太陽光といっても屋根に設置するのではなく、持ち運びできる小型のパネルをベランダなどに置くもので、照明などちょっとした用途に使うことができます。既成品として販売されていることもありますが、自分で作ることもでき、材料は、インターネット通販とホームセンターで調達できます。<br>　晴れた日にはふとんを干すような感覚で、日光にあててバッテリーを充電させ、充電された分で活用することができます。曇りの日などは、電気を使うことができない場合があります。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWecocute'] = { mid:"101",  name:"mHWecocute",  title:"給湯器をエコキュートに買い換える",  easyness:"2",  refCons:"consHWsum",  titleShort:"エコキュート", level:"",  figNum:"8",  lifeTime:"10",  price:"400000",  roanShow:"1",  standardType:"電気温水器",  subsidy :"",  advice:"エコキュート（自然冷媒ヒートポンプ給湯器）は、エアコンの室外機のような装置がついており、外気の熱を利用してお湯を沸かすため、電気温水器より3倍以上効率がよくなります。貯湯槽にためたお湯を使い切るような、家族人数が多く、毎日欠かさずお風呂に入る家庭にはお勧めです。<br>　また、ふだんのお湯の使い方を考慮して控えめに沸かす設定をすると、さらに省エネにつながります。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWecojoze'] = { mid:"102",  name:"mHWecojoze",  title:"給湯器をエコジョーズ（潜熱回収型）に買い換える",  easyness:"2",  refCons:"consHWsum",  titleShort:"エコジョーズ", level:"",  figNum:"10",  lifeTime:"10",  price:"200000",  roanShow:"",  standardType:"既存型",  subsidy :"",  advice:"エコジョーズ（潜熱回収型）は、水蒸気として逃げていた熱も回収する仕組みのため、既存のガス給湯器に比べて効率が1割以上向上しています。既存のガス給湯器とほぼ同じ形ですが、熱回収をするために少し大型になっており、また熱を回収する際に発生する水を流すドレンもついています。ガス会社によってはエコジョーズ料金により、ガス代が割り引かれる場合もあります。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWecofeel'] = { mid:"103",  name:"mHWecofeel",  title:"給湯器をエコフィール（潜熱回収型）に買い換える",  easyness:"1",  refCons:"consHWsum",  titleShort:"エコフィール", level:"",  figNum:"10",  lifeTime:"10",  price:"250000",  roanShow:"",  standardType:"既存型",  subsidy :"",  advice:"エコフィール（潜熱回収型）は、水蒸気として逃げていた熱も回収する仕組みのため、効率が1割以上向上しています。既存の灯油ボイラーとほぼ同じ形ですが、熱回収をするために少し大型になっており、また熱を回収する際に発生する水を流すドレンもついています。灯油ではなくガスのタイプは「エコジョース」といいます。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWenefarm'] = { mid:"105",  name:"mHWenefarm",  title:"給湯器をエネファーム（燃料電池）に買い換える",  easyness:"0.5",  refCons:"consHWsum",  titleShort:"エネファーム", level:"5",  figNum:"10",  lifeTime:"10",  price:"1200000",  roanShow:"1",  standardType:"エコジョーズ",  subsidy :"",  advice:"エネファームは、燃料電池で発電をしながらお湯をわかす効率がよい装置です。家庭で消費する電気の分だけ発電を行い、発生した余熱をお湯としてためて利用することができます。電気やお湯をたくさん使う家庭で、大きな省エネ効果が期待できます。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWsolarHeater'] = { mid:"106",  name:"mHWsolarHeater",  title:"太陽熱温水器（自然循環式）を設置して利用する",  easyness:"1",  refCons:"consHWsum",  titleShort:"太陽熱温水器", level:"",  figNum:"9",  lifeTime:"10",  price:"400000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"暖かい時期の晴れた日なら、太陽の熱で沸かしたお湯だけでお風呂に入ることができます。冬でも加温することで利用することができ、お湯のエネルギー消費を大幅に減らせます。比較的簡単なしくみでお湯をわかすことができ、有効な温暖化対策として、世界中で利用が拡大しています。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWsolarSystem'] = { mid:"107",  name:"mHWsolarSystem",  title:"ソーラーシステム（強制循環式）を設置して利用する",  easyness:"1",  refCons:"consHWsum",  titleShort:"ソーラーシステム", level:"",  figNum:"9",  lifeTime:"10",  price:"600000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"貯湯タンクを地上に置いて利用する太陽熱温水器です。屋根にタンクがないので、負荷がかかりません。暖かい時期の晴れた日なら、太陽の熱で沸かしたお湯だけでお風呂に入ることができます。冬でも加温することで利用することができ、お湯のエネルギー消費を大幅に減らせます。比較的簡単なしくみでお湯をわかすことができ、有効な温暖化対策として、世界中で利用が拡大しています。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWshowerHead'] = { mid:"108",  name:"mHWshowerHead",  title:"節水シャワーヘッドを取り付けて利用する",  easyness:"5",  refCons:"consHWshower",  titleShort:"節水シャワーヘッド", level:"",  figNum:"11",  lifeTime:"10",  price:"2000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"シャワーの持ち手（ヘッド）の部分を取り替えることができるようになっています。お湯が出る穴を小さくしてあり、勢いよくお湯が出てくるほか、手元で止水できるものもあり、3割程度お湯の利用を減らすことができます。ホームセンターや家電量販店などで購入できます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWshowerTime'] = { mid:"109",  name:"mHWshowerTime",  title:"シャワーの利用を1人1日1分短くする",  easyness:"4",  refCons:"consHWshower",  titleShort:"シャワー1人1分短縮", level:"",  figNum:"11",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"シャワーのエネルギー消費はとても大きく、お湯を出している状態で、テレビ300台分のエネルギーが消費されます。少し止めるだけでも大きな削減になります。身体を洗っているときには止めるなど、利用時間を減らすよう気を付けましょう。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWshowerTime30'] = { mid:"110",  name:"mHWshowerTime30",  title:"シャワーの利用時間を3割短くする",  easyness:"3",  refCons:"consHWshower",  titleShort:"シャワー3割短縮", level:"",  figNum:"11",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"シャワーのエネルギー消費はとても大きく、お湯を出している状態で、テレビ300台分のエネルギーが消費されます。少し止めるだけでも大きな削減になります。身体を洗っているときには止めるなど、利用時間を減らすよう気を付けましょう。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWkeep'] = { mid:"111",  name:"mHWkeep",  title:"風呂に家族が続けて入り追い焚きをしない",  easyness:"3",  refCons:"consHWtub",  titleShort:"風呂の保温をしない", level:"",  figNum:"12",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"追い焚きでは、風呂のお湯をいちど外に出し、給湯器まで送る必要があります。この間に冷えてしまい、余分なエネルギーがかかります。追い炊き機能を使わずに、続けてはいることが大きな削減になります。また浴槽にフタをすることでも、冷めにくくすることもできます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWsaveMode'] = { mid:"112",  name:"mHWsaveMode",  title:"エコキュートを「節約モード」に設定する",  easyness:"3",  refCons:"consHWsum",  titleShort:"給湯節約モード", level:"",  figNum:"8",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"エコキュートは夜間に沸かす湯量の設定ができるようになっています。お湯切れがないように余裕に沸かすと、保温時のロスが大きくなります。通常の使い方をする日で、特に湯切れなどない場合には、節約モードに設定することで、省エネになります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWstopAutoKeep'] = { mid:"113",  name:"mHWstopAutoKeep",  title:"自動保温を続けるのでなく、次の人が入る直前に沸かし直す",  easyness:"3",  refCons:"consHWtub",  titleShort:"自動保温をしない", level:"",  figNum:"12",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"自動保温では、頻繁に風呂のお湯を屋外の給湯器まで送り出して温めるため、配管部分の熱の無駄が大きくなります。続けて入ることで保温しなくてもすみますが、時間があいて冷めてしまう場合には自動保温をせず、後から入る直前に温め直すことで省エネになります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWinsulation'] = { mid:"114",  name:"mHWinsulation",  title:"断熱型の浴槽にリフォームする",  easyness:"1",  refCons:"consHWtub",  titleShort:"断熱浴槽", level:"",  figNum:"12",  lifeTime:"10",  price:"600000",  roanShow:"",  standardType:"普及型",  subsidy :"",  advice:"浴槽が発泡スチロールなどの断熱材で覆われており、お湯が冷めにくくなっているタイプが増えています。浴槽のリフォーム工事が必要になりますが、冷めにくい分、追い炊きをしなくてすみます。あわせて、浴室もユニットバスにすると、浴室全体からの熱も逃げにくくなります。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWonlyShower'] = { mid:"115",  name:"mHWonlyShower",  title:"夏場はシャワーだけですませて浴槽にお湯を張らない",  easyness:"3",  refCons:"consHWtub",  titleShort:"夏に浴槽のお湯をためない", level:"",  figNum:"11",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"浴槽のお湯の量は、シャワーを使っている時間に換算すると10～20分に相当します。自動湯張りをせずに、浴槽のお湯だけを使って洗う家庭ではかえって増える場合もありますが、シャワーを併用している場合には浴槽の分が削減になります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWdishTank'] = { mid:"116",  name:"mHWdishTank",  title:"食器洗いでお湯を流しっぱなしにしない",  easyness:"2",  refCons:"consHWdishwash",  titleShort:"食器流し洗い", level:"",  figNum:"13",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"洗剤で洗っているときにはお湯を止めるなど、なるべくお湯を出す時間を短く工夫してください。油汚れは古布等で先にふき取っておくと、すすぎも早く済みます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWdishWater'] = { mid:"117",  name:"mHWdishWater",  title:"水が冷たくない時期には水で食器を洗う",  easyness:"2",  refCons:"consHWdishwash",  titleShort:"食器水洗い", level:"",  figNum:"13",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"暖かい季節には、お湯を使わなくても十分すすぐことができます。たとえば食器洗いでお湯を10分使う場合、ポット3杯分の熱湯を沸かすだけのエネルギーが消費されます。油汚れは古布等でふき取っておくなど、工夫することで食器洗いも早く済みます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mCKdishWasher'] = { mid:"118",  name:"mCKdishWasher",  title:"食器洗い乾燥機を使う",  easyness:"2",  refCons:"consHWdishwash",  titleShort:"食器洗浄機", level:"",  figNum:"15",  lifeTime:"10",  price:"80000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"食器をお湯で流し洗いするのに比べると、お湯をためて洗浄しているため、食器洗浄乾燥機のほうが省エネとなります。なおお湯ではなく水で洗う場合には、食器洗浄機よりも省エネとなります。手洗いで工夫するのも有効な方法です。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWtap'] = { mid:"119",  name:"mHWtap",  title:"台所・洗面所に節湯水栓を設置する",  easyness:"2",  refCons:"consHWsum",  titleShort:"節湯水栓", level:"",  figNum:"13",  lifeTime:"20",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"手元ですぐ止められるようにしたり、シングルレバーを左に向けないとお湯がでないしくみにするなど、使い勝手は同じでも、お湯の消費量を2割以上減らせる機器があります。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWreplaceToilet5'] = { mid:"120",  name:"mHWreplaceToilet5",  title:"節水トイレを設置する",  easyness:"1",  refCons:"consHWtoilet",  titleShort:"節水トイレ", level:"",  figNum:"19",  lifeTime:"10",  price:"30000",  roanShow:"",  standardType:"既存型",  subsidy :"",  advice:"トイレ本体を工事して交換する必要がありますが、水の量を以前よりも半分以下に抑えることができます。以前は13リットル程度必要だったものが、4-6リットル程度で使えるようになっており、水道代を大きく削減できます。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWreplaceToilet'] = { mid:"121",  name:"mHWreplaceToilet",  title:"瞬間式の温水洗浄便座に買い替える",  easyness:"1",  refCons:"consHWtoilet",  titleShort:"瞬間式便座", level:"",  figNum:"19",  lifeTime:"10",  price:"30000",  roanShow:"",  standardType:"既存型",  subsidy :"",  advice:"新製品では省エネ機能があり、ふたを開けた瞬間に温めるタイプなど、消費電力が少なくてすみます。カタログに表示されている年間消費電力量を参考に省エネ型を選んでください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHWtemplatureToilet'] = { mid:"122",  name:"mHWtemplatureToilet",  title:"保温便座の温度設定を下げる",  easyness:"3",  refCons:"consHWtoilet",  titleShort:"便座温度調節", level:"",  figNum:"19",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"寒くない時期は保温を切ったり、温度設定を低めに設定することで省エネができます。便座にカバーをかけると、冷たさを感じにくくなります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHWcoverTilet'] = { mid:"123",  name:"mHWcoverTilet",  title:"保温洗浄便座のふたをしめる",  easyness:"3",  refCons:"consHWtoilet",  titleShort:"便座のふたを閉める", level:"",  figNum:"19",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"便座のふたを上げた状態にしておくと、保温の熱が逃げやすく、消費電力が増えます。用を終えたら、ふたを閉めることで省エネになります。寒くなければ、保温をしないようにすることも省エネにつながります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mACreplace'] = { mid:"201",  name:"mACreplace",  title:"エアコンを省エネ型に買い替える",  easyness:"1",  refCons:"consAC",  titleShort:"省エネエアコン", level:"",  figNum:"1",  lifeTime:"10",  price:"160000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"同じだけ冷暖房をしても、15年に比べると半分くらいの消費電力ですむ省エネ性能の高いエアコンがあります。選ぶ時には、統一省エネラベルの★マークの数が多いものや、年間電気代の表示を参考に省エネ型を選んでください。暖房の性能もあがっており、ガスや灯油の暖房に比べてもCO2を削減することができます。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mACreplaceHeat'] = { mid:"202",  name:"mACreplaceHeat",  title:"エアコンを省エネ型に買い替え、エアコンで暖房する",  easyness:"2",  refCons:"consAC",  titleShort:"省エネエアコン＋暖房", level:"",  figNum:"1",  lifeTime:"10",  price:"160000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"同じだけ冷暖房をして、15年に比べると半分くらいの消費電力ですむ省エネ性能の高いエアコンがあります。エアコンは室外の熱を利用するために、ガスや灯油などの暖房とくらべても、CO2排出量が少なくなります。選ぶ時には、統一省エネラベルの★マークの数が多いものや、年間電気代の表示を参考に省エネ型を選んでください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mACchangeHeat'] = { mid:"203",  name:"mACchangeHeat",  title:"暖房をエアコンでする",  easyness:"2",  refCons:"consACheat",  titleShort:"エアコン暖房", level:"",  figNum:"1",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"エアコンで暖房をすると、外気の熱を利用するため、ガスや灯油の暖房に比べて大幅にCO2を削減でき、光熱費の削減にもつながります。なお、床までしっかり暖気が届かないと暖まりませんから、強風設定で暖房するか、うちわなどを活用してください。また、最近のエアコンは床まで暖める機能が充実していますので、ぜひ試してみてください。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTchangeHeat'] = { mid:"204",  name:"mHTchangeHeat",  title:"家の暖房をエアコンでする",  easyness:"1",  refCons:"consHTsum",  titleShort:"エアコン暖房", level:"",  figNum:"1",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"エアコンで暖房をすると、外気の熱を利用するため、ガスや灯油の暖房に比べて大幅にCO2を削減でき、光熱費の削減にもつながります。なお、床までしっかり暖気が届かないと暖まりませんから、強風設定で暖房するか、うちわなどを活用してください。また、最近のエアコンは床まで暖める機能が充実していますので、ぜひ試してみてください。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mCOsunCut'] = { mid:"205",  name:"mCOsunCut",  title:"冷房で、すだれ等を使い日射をカットする",  easyness:"4",  refCons:"consCOsum",  titleShort:"冷房日射カット", level:"",  figNum:"1",  lifeTime:"5",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"冷房時に日射が入るのは、窓にストーブを置いているようなものです。遮るほうが省エネになり、より涼しく過ごすことができます。なおカーテンでは窓の内側のカーテンが暖まりますので、窓の外にすだれ・よしずをするほうが涼しくなります。また、5月頃から、ゴーヤ・朝顔・ヘチマなどを植えて育てると、夏にはりっぱな「緑のカーテン」ができあがり、涼しく過ごすことができます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mCOtemplature'] = { mid:"206",  name:"mCOtemplature",  title:"冷房の温度設定を控えめ（28℃）にする",  easyness:"3",  refCons:"consACcool",  titleShort:"冷房設定温度", level:"",  figNum:"1",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"省エネを考えた暖房設定温度の目安は20℃以下です。「暖かくする」のではなく「寒くないようにする」程度に考えてみてください。寒さの感じ方には個人差があるので無理をする必要はありませんが、厚着をしたり、暖まる食事をとるなどして、工夫をしてみてください。1℃控えめにすることで、CO2排出量や光熱費をおよそ1割削減できます。また季節の終わりには、早めに冷暖房器具をしまうことも効果的です。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTtemplature'] = { mid:"207",  name:"mHTtemplature",  title:"厚着をして暖房の温度設定を控えめ（20℃）にする",  easyness:"3",  refCons:"consACheat",  titleShort:"暖房設定温度", level:"",  figNum:"3",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"省エネを考えた冷房設定温度の目安は28℃以上です。「涼しくする」のではなく、「暑くないようにする」程度に考えてみてください。暑さの感じ方には個人差があるので無理をする必要はありませんが、扇風機を活用したり、薄着をするなどして工夫をしてみてください。窓をあけて風が入ると涼しく感じますし、風鈴の音なども、涼しく感じさせてくれます。1℃控えめにすることで、CO2排出量や光熱費をおよそ1割削減できます。また季節の終わりには、早めに冷暖房器具をしまうことも効果的です。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTwindowSheet'] = { mid:"208",  name:"mHTwindowSheet",  title:"暖房時に、窓用の断熱シートを貼る",  easyness:"3",  refCons:"consACheat",  titleShort:"窓断熱シート", level:"",  figNum:"4",  lifeTime:"3",  price:"3000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"断熱シート（いわゆるプチプチシートのようなもの）は、ホームセンター等で売られています。窓をきれいにしてから、霧吹きをかけ、その水だけで窓に貼り付けることができます。断熱効果があるだけでなく、結露も抑えることができます。窓から吹き下ろしてくる冷たい風も和らぎ、快適性も向上します。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHTdouble'] = { mid:"209",  name:"mHTdouble",  title:"窓・サッシを複層ガラスにする",  easyness:"1",  refCons:"consACheat",  titleShort:"複層ガラス", level:"5",  figNum:"4",  lifeTime:"30",  price:"100000",  roanShow:"",  standardType:"",  subsidy :"家の窓全体の断熱工事をする場合、工事にかかった費用に応じて、固定資産税の控除や、ローン残高に応じた所得税控除の制度があります。",  advice:"暖房時は窓やサッシから逃げる熱の割合が多く、通常のシングルガラスを複層ガラスに取り替えることで熱の逃げ方を半分程度に抑えることができます。省エネだけでなく、結露がつきにくくなるというメリットもあります。窓から吹き下ろしてくる冷たい風も和らぎ、快適性も向上します。家屋に応じた手法がありますので、工務店などに相談してください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHTlowe'] = { mid:"210",  name:"mHTlowe",  title:"窓・サッシを樹脂枠low-Eガラスにする",  easyness:"1",  refCons:"consACheat",  titleShort:"樹脂枠low-Eガラス", level:"",  figNum:"4",  lifeTime:"30",  price:"150000",  roanShow:"",  standardType:"",  subsidy :"家の窓全体の断熱工事をする場合、工事にかかった費用に応じて、固定資産税の控除や、ローン残高に応じた所得税控除の制度があります。",  advice:"暖房時は窓やサッシから逃げる熱の割合が多く、取り替えることで熱の逃げ方を半分程度に抑えることができます。通常の二重ガラスに比べて、断熱にすぐれており、枠からの熱ロスも減らせます。省エネだけでなく、結露がつきにくくなるというメリットもあります。家屋に応じた手法がありますので、工務店などに相談してください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHTuchimado'] = { mid:"211",  name:"mHTuchimado",  title:"内窓をとりつける",  easyness:"2",  refCons:"consACheat",  titleShort:"内窓", level:"5",  figNum:"4",  lifeTime:"30",  price:"60000",  roanShow:"",  standardType:"",  subsidy :"家の窓全体の断熱工事をする場合、工事にかかった費用に応じて、固定資産税の控除や、ローン残高に応じた所得税控除の制度があります。",  advice:"暖房時は窓やサッシから逃げる熱の割合が多く、現在の窓やサッシの内側に追加して「内窓」をつけることでより熱が逃げにくくなります。内窓は比較的工事費が安く、約1時間で工事も完了し、結露防止や防犯にも効果があります。詳しくは工務店などに相談してください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHTdoubleGlassAll'] = { mid:"212",  name:"mHTdoubleGlassAll",  title:"全ての部屋の窓ガラスを複層ガラスに置き換える",  easyness:"1",  refCons:"consHTsum",  titleShort:"全居室を複層ガラスに", level:"",  figNum:"4",  lifeTime:"30",  price:"100000",  roanShow:"",  standardType:"",  subsidy :"家の窓全体の断熱工事をする場合、工事にかかった費用に応じて、固定資産税の控除や、ローン残高に応じた所得税控除の制度があります。",  advice:"暖房時は窓やサッシから逃げる熱の割合が多く、通常のシングルガラスを複層ガラスに取り替えることで熱の逃げ方を半分程度に抑えることができます。省エネだけでなく、結露がつきにくくなるというメリットもあります。窓から吹き下ろしてくる冷たい風も和らいだり、冬の朝方の寒さが改善されたりなど、快適性も向上します。家屋に応じた手法がありますので、工務店などに相談してください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHTuchimadoAll'] = { mid:"213",  name:"mHTuchimadoAll",  title:"全ての部屋に内窓をとりつける",  easyness:"1",  refCons:"consHTsum",  titleShort:"全居室を内窓に", level:"",  figNum:"4",  lifeTime:"30",  price:"100000",  roanShow:"",  standardType:"",  subsidy :"家の窓全体の断熱工事をする場合、工事にかかった費用に応じて、固定資産税の控除や、ローン残高に応じた所得税控除の制度があります。",  advice:"暖房時は窓やサッシから逃げる熱の割合が多く、現在の窓やサッシの内側に追加して「内窓」をつけることでより熱が逃げにくくなります。内窓は比較的工事費が安く、約1時間で工事も完了し、結露防止や防犯にも効果があります。窓から吹き下ろしてくる冷たい風も和ら、冬の朝方の寒さが改善されたりなど、快適性も向上します。詳しくは工務店などに相談してください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHTloweAll'] = { mid:"214",  name:"mHTloweAll",  title:"全ての部屋の窓・サッシを樹脂枠low-Eガラスにする",  easyness:"1",  refCons:"consHTsum",  titleShort:"全居室を樹脂枠low-Eガラスに", level:"",  figNum:"4",  lifeTime:"30",  price:"150000",  roanShow:"",  standardType:"",  subsidy :"家の窓全体の断熱工事をする場合、工事にかかった費用に応じて、固定資産税の控除や、ローン残高に応じた所得税控除の制度があります。",  advice:"暖房時は窓やサッシから逃げる熱の割合が多く、取り替えることで熱の逃げ方を半分程度に抑えることができます。通常の二重ガラスに比べて、断熱にすぐれており、枠からの熱ロスも減らせます。省エネだけでなく、結露がつきにくくなるというメリットもあります。窓から吹き下ろしてくる冷たい風も和ら、冬の朝方の寒さが改善されたりなど、快適性も向上します。家屋に応じた手法がありますので、工務店などに相談してください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mACfilter'] = { mid:"215",  name:"mACfilter",  title:"エアコンのフィルターを掃除する",  easyness:"2",  refCons:"consACheat",  titleShort:"フィルター掃除", level:"5",  figNum:"1",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"エアコンは1ヶ月利用するごとにフィルター掃除するのが望ましいです。フィルターの目が詰まると、送風が弱くなり、特に暖房での効率が大きく落ちてしまいます。特にキッチンを含む部屋では、油煙がつきやすいのでこまめに掃除してください。最近のエアコンでは、自動的にフィルターを掃除する機種もあります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTtime'] = { mid:"216",  name:"mHTtime",  title:"暖房の使用時間を1時間短くする",  easyness:"3",  refCons:"consACheat",  titleShort:"暖房1時間短縮", level:"",  figNum:"3",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"暖房はつい長い時間つけっぱなしにしがちです。暖かくなったら止めるようにしましょう。就寝前や外出時などは30分前に止めるのも一つの方法です。また、人がいない部屋を暖房するのは無駄ですので、なるべく切るようにしましょう。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTpartialHeating'] = { mid:"217",  name:"mHTpartialHeating",  title:"こたつやホットカーペットを活用して、部屋暖房を控える",  easyness:"2",  refCons:"consACheat",  titleShort:"こたつ・ホットカーペット", level:"",  figNum:"3",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"こたつやホットカーペットなどの部分暖房は、身体の近くだけを温めるので、消費エネルギーが少なくなっています。部屋暖房の設定温度を大きく下げても、同じ快適性を維持できます。特に、吹き抜け構造だったり、暖房部屋から階段が上階に続いている構造の場合、せっかく温めた空気が天井に抜けてしまい、部屋を温めるのに効率が悪くなります。こうした場合には、足元を温める暖房も検討してみてください。靴下をはいたり、厚着をすることも効果的です。<br>　こたつやホットカーペットを使う場合には、床との間に断熱シートを敷いたり、こたつの掛け布団も厚めにすると、より消費電力を減らせます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTceiling'] = { mid:"218",  name:"mHTceiling",  title:"暖房時に天井の暖気をかきまぜる",  easyness:"2",  refCons:"consACheat",  titleShort:"サーキュレータ", level:"",  figNum:"3",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"部屋暖房をしていると、床に比べて天井のほうが5～10℃近くも温度が高くなっていることが多くあります。うちわなどでかきまぜたり、サーキュレータや扇風機を上向きにしてかきまぜることで、暖かい空気を床まで届けることができ、快適に過ごせます。靴下をはいたり、厚着をすることも効果的です。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTareaLimit'] = { mid:"219",  name:"mHTareaLimit",  title:"暖房時に部屋のドアやふすまを閉め、暖房範囲を小さくする",  easyness:"2",  refCons:"consACheat",  titleShort:"暖房範囲", level:"5",  figNum:"3",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"広い部屋を暖房するのには多くのエネルギーが必要です。ふすまや扉などで部屋を区切ると、小さい暖房器具でもよく暖まります。逆に吹き抜け構造など天井が高い場合は、多くの暖房が必要になります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTdanran'] = { mid:"220",  name:"mHTdanran",  title:"家族だんらんで一部屋で過ごすようにする",  easyness:"3",  refCons:"consHTsum",  titleShort:"家族だんらん", level:"",  figNum:"3",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"家族が別々の部屋で過ごすと、それぞれに暖房や照明をつける必要があります。いっしょの部屋で過ごすことで、暖房も照明も減らすことができます。ぜひ団らんの時間を楽しみながら、省エネをしてみてください。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTbiomass'] = { mid:"221",  name:"mHTbiomass",  title:"薪ストーブ（ペレットストーブ）を導入する",  easyness:"1",  refCons:"consACheat",  titleShort:"薪・ペレットストーブ", level:"",  figNum:"3",  lifeTime:"20",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"薪ストーブもしくはペレットストーブを使うと、石油やガスなどの化石燃料を使わないため二酸化炭素排出量を減らすことができます。昔からの暖房燃料ですが、むしろ暖炉などおしゃれな作りで、都市部でも導入する事例が増えています。ペレットストーブは、燃料を自動的に供給するために、手間がかからないのもメリットです。設置には煙突の設置など、工事が必要になります。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mHTcentralNotUse'] = { mid:"222",  name:"mHTcentralNotUse",  title:"セントラルヒーティングで使っていない部屋の設定温度を下げる",  easyness:"2",  refCons:"consHTsum",  titleShort:"未使用部屋の暖房温度", level:"5",  figNum:"3",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"セントラルヒーティングをしている場合には、使わない部屋まで暖めていることになります。使わない部屋の暖房を止めてしまうと結露・凍結などの問題がある場合には、そうならない程度に暖房設定を控えめにしてください。人がいる部屋での暖房設定の目安は20℃です。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mHTkanki'] = { mid:"223",  name:"mHTkanki",  title:"全熱交換換気装置を設置する",  easyness:"1",  refCons:"consHTsum",  titleShort:"全熱交換換気", level:"",  figNum:"3",  lifeTime:"20",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"新しい家では換気設備の導入が義務付けられていますが、暖房をしているときには、温かい空気を捨ててしまうことにもなります。熱を回収して、逃げる量を少なくできる換気システムにすると、大きく熱のロスを減らすことができます。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mPTstopPot'] = { mid:"301",  name:"mPTstopPot",  title:"電気ポットで保温をしない",  easyness:"2",  refCons:"consCKpot",  titleShort:"ポット保温しない", level:"",  figNum:"17",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"電気ポットでは、保温のために多くの電気が消費されています。必要に応じてお湯を沸かすようにするか、魔法瓶を活用してみてください。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mPTstopPotNight'] = { mid:"302",  name:"mPTstopPotNight",  title:"外出時や夜間に電気ポットの保温を止める",  easyness:"3",  refCons:"consCKpot",  titleShort:"夜間保温停止", level:"",  figNum:"17",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"外出時や夜間など、長時間お湯を使わない場合には、止めておくことで保温電力を削減できます。炊飯ジャーや、便座の保温なども、同様に止めておくほうが省エネになります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mPTstopRiceCooker'] = { mid:"303",  name:"mPTstopRiceCooker",  title:"炊飯ジャーの保温をやめる",  easyness:"3",  refCons:"consCKrice",  titleShort:"ジャー保温", level:"",  figNum:"18",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"炊飯ジャーの保温を止めて、食べるときに電子レンジで温め直すほうが省エネになります。長時間保温をすると、ご飯が変色することもあり、常温保温のほうがおいしくいただけます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mPTreplacePot'] = { mid:"304",  name:"mPTreplacePot",  title:"省エネタイプの電気ポットに買い替える",  easyness:"2",  refCons:"consCKpot",  titleShort:"省エネ電気ポット", level:"",  figNum:"17",  lifeTime:"",  price:"",  roanShow:"",  standardType:"既存型",  subsidy :"",  advice:"魔法瓶のような断熱がされている電気ポットがあり、保温の電気消費が少なくてすみます。店頭では保温消費電力が表示されていることがあり、これを参考にしてください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mCKflame'] = { mid:"305",  name:"mCKflame",  title:"鍋から炎がはみ出さないようにする",  easyness:"2",  refCons:"consCKcook",  titleShort:"調理炎調整", level:"",  figNum:"14",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"鍋底から炎がはみ出すのは、ガスが無駄になるだけで、調理時間の短縮にはなりません。鍋底からはみ出さない程度に調節して使いましょう。このほかにも、段取りよく調理をする工夫によって、ガスの消費を減らすことができます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mDRsolar'] = { mid:"401",  name:"mDRsolar",  title:"晴れた日は衣類乾燥機や乾燥機能を使わずに天日乾燥させる",  easyness:"2",  refCons:"consDRsum",  titleShort:"天日干し", level:"",  figNum:"16",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"乾燥機能は便利ですが、洗濯の10倍以上のエネルギーがかかります。なるべく天日干しをして、乾燥機能を使わないことが効果的です。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mDRheatPump'] = { mid:"402",  name:"mDRheatPump",  title:"ヒートポンプ式の衣類乾燥ができる洗濯機に買い替える",  easyness:"1",  refCons:"consDRsum",  titleShort:"ヒートポンプ乾燥", level:"",  figNum:"16",  lifeTime:"10",  price:"140000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"衣類乾燥機や乾燥機能付き洗濯機の中で、ヒートポンプ式のものは、通常の乾燥機に比べてエネルギー消費が半分程度で済みます。よく乾燥機能を利用する場合には、光熱費の削減額も大きく効いてきます。ただし、乾燥機能自体が多くのエネルギーを使うため、なるべく乾燥機能を使わないことが望ましいです。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mLIceilingLED'] = { mid:"501",  name:"mLIceilingLED",  title:"蛍光灯器具をLEDシーリングライトに付け替える",  easyness:"4",  refCons:"consLI",  titleShort:"LEDライト", level:"",  figNum:"6",  lifeTime:"20",  price:"",  roanShow:"",  standardType:"蛍光灯",  subsidy :"",  advice:"LEDの省エネ性能は高く、長持ちします。カバーの中に虫が入らないため、掃除の手間も省くことができます。照明器具から取り替えますが、ソケットがあるので、通常は電気屋に頼まなくても交換はできます。色合いなども調整したり、細かく明るさを調整したりすることもできます。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mLILED'] = { mid:"502",  name:"mLILED",  title:"LEDに付け替える",  easyness:"2",  refCons:"consLI",  titleShort:"LED電球", level:"",  figNum:"5",  lifeTime:"40000h",  price:"2000",  roanShow:"",  standardType:"電球",  subsidy :"",  advice:"電球と同じソケットを使っており、電球が切れたときにそのまま付け替えることができます。電気の消費を8割削減でき、寿命は40倍以上になります。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mLIsensor'] = { mid:"503",  name:"mLIsensor",  title:"人感センサー式に付け替える",  easyness:"2",  refCons:"consLI",  titleShort:"センサー照明", level:"",  figNum:"5",  lifeTime:"10",  price:"",  roanShow:"",  standardType:"電球",  subsidy :"",  advice:"玄関の照明では、ずっと明かりをつけているより、人が近づくと点くため、防犯性能も高いとされています。点いている時間が短い分、大幅な省エネができます。同じ人感センサーとしては、廊下などに設置をして、人が通るときだけ照らすタイプも実用的で効果的です。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mLItime'] = { mid:"504",  name:"mLItime",  title:"照明を使う時間を1時間短くする",  easyness:"3",  refCons:"consLI",  titleShort:"照明短縮", level:"",  figNum:"6",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"点けるときに多くの電気が流れますが、ほんの一瞬であるため、結果的にこまめに消すほうが省エネになります。部屋を離れるときには消す習慣が大切です。また、夜に明るい光をあびると、睡眠のサイクルが狂ってしまい、身体にとってよくないことになります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mLIoff'] = { mid:"505",  name:"mLIoff",  title:"部屋を出るときに照明を消す",  easyness:"4",  refCons:"consLI",  titleShort:"照明消灯", level:"",  figNum:"6",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"部屋を離れるときには、こまめに照明を消すようにしましょう。すぐに戻ってくる予定でも、点けるときに多くの電気が流れますが、ほんの一瞬であるため、結果的にこまめに消すほうが省エネになります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mTVreplace'] = { mid:"601",  name:"mTVreplace",  title:"省エネ性能の高いテレビに買い替える",  easyness:"2",  refCons:"consTV",  titleShort:"省エネテレビ購入", level:"",  figNum:"7",  lifeTime:"10",  price:"40000",  roanShow:"",  standardType:"普及型",  subsidy :"",  advice:"省エネ性能があがっているため、同じサイズであれば半分以下の消費電力になるテレビが販売されています。店頭では、なるべく年間電気代が安いものを選ぶようにしてください。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mTVradio'] = { mid:"602",  name:"mTVradio",  title:"テレビの時間の半分をラジオにする",  easyness:"1",  refCons:"consTVsum",  titleShort:"ラジオ", level:"",  figNum:"7",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"ラジオはテレビの10～100分の1の消費電力ですみます。寂しいためにテレビをつけている場合には、半分程度の時間は、ラジオやCDなどに代えてみてください。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mTVtime'] = { mid:"603",  name:"mTVtime",  title:"テレビを点ける時間を1日1時間短くする",  easyness:"3",  refCons:"consTV",  titleShort:"テレビ短縮", level:"",  figNum:"7",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"あらかじめ見る番組を決め、見終えたら消すようにしましょう。点けっぱなしにしていると、つい次の番組まで見てしまうこともあります。またテレビゲームの場合にも、長時間しがちですので、使う時間を短くするようにしましょう。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mTVbright'] = { mid:"604",  name:"mTVbright",  title:"テレビの画面を明るすぎないよう調整する",  easyness:"2",  refCons:"consTV",  titleShort:"テレビ明るさ調節", level:"",  figNum:"7",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"テレビの画面の明るさを調節できるようになっています。販売時には明るく設定がされており、このままでは家ではまぶしすぎ、消費電力も多くなります。明るさを控えめに設定することで、2～4割程度消費電力が削減されます。新しいテレビでは、センサーで自動調節するタイプもあります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mRFreplace'] = { mid:"701",  name:"mRFreplace",  title:"冷蔵庫を省エネ型に買い替える",  easyness:"2",  refCons:"consRF",  titleShort:"省エネ冷蔵庫", level:"",  figNum:"2",  lifeTime:"10",  price:"150000",  roanShow:"",  standardType:"普及型",  subsidy :"",  advice:"以前の機種に比べると半分くらいの電気ですむ省エネ型冷蔵庫があります。選ぶ時には、統一省エネラベルの★マークの数が多いものや、年間電気代の表示を参考に省エネ型を選んでください。買換のときには、古い冷蔵庫は家電リサイクルの制度で引き取ってもらうようにしましょう。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mRFstop'] = { mid:"702",  name:"mRFstop",  title:"冷蔵庫のうち１台を止める",  easyness:"2",  refCons:"consRF",  titleShort:"冷蔵庫停止", level:"",  figNum:"2",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"2台以上使っている場合には、1台を止めてください。小型の冷蔵庫でも大型と同じくらい多くの電気を消費します使わないでおくと「もったいない」と感じるかもしれませんが、電気を入れているだけで大きな環境負荷が生じますので、使わないほうが望ましいです。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mRFwall'] = { mid:"703",  name:"mRFwall",  title:"冷蔵庫を壁から離す",  easyness:"4",  refCons:"consRF",  titleShort:"冷蔵庫位置", level:"",  figNum:"2",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"冷蔵庫は壁から5cm程度離すのが目安です。冷蔵庫は側面や天井面から熱を逃がしていますが、壁に接していると熱が逃げにくくなり、消費電力が1割程度増えてしまいます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mRFtemplature'] = { mid:"704",  name:"mRFtemplature",  title:"冷蔵庫の温度設定を控えめにする",  easyness:"4",  refCons:"consRF",  titleShort:"冷蔵温度", level:"",  figNum:"2",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"冷蔵庫は温度調節ができます。強から中へ、中から弱へするとそれぞれ1割程度省エネができます。食品の傷みがやや速くなりますので、支障がないか確認しながら試してみてください。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mCRreplace'] = { mid:"801",  name:"mCRreplace",  title:"エコカーに買い替える",  easyness:"2",  refCons:"consCR",  titleShort:"車買い替え", level:"",  figNum:"21",  lifeTime:"8",  price:"1800000",  roanShow:"",  standardType:"普及型",  subsidy :"エコカーの導入にあたっては、「減税」のメリットが得られます。",  advice:"ハイブリッド車や電気自動車以外にも、技術改善により、既存の燃料消費が半分程度で済む低燃費車が開発されて販売されています。購入時には燃費を考慮して選んで下さい。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mCRreplaceElec'] = { mid:"802",  name:"mCRreplaceElec",  title:"電気自動車を導入する",  easyness:"1",  refCons:"consCR",  titleShort:"電気自動車", level:"",  figNum:"21",  lifeTime:"7",  price:"3000000",  roanShow:"",  standardType:"",  subsidy :"",  advice:"ガソリンの代わりに充電式電池に電気をため、エンジンの代わりにモーターを回して走ります。エンジンに比べて効率が高く、十分実用的な車として販売がされています。ただし充電スタンドはまだ少なく、充電に時間がかかるため、夜間に充電しておくと便利です。",   lifestyle:"",   season:"wss"};
	D6.scenario.defMeasures['mCRecoDrive'] = { mid:"803",  name:"mCRecoDrive",  title:"アイドリングストップなどエコドライブに心がける",  easyness:"3",  refCons:"consCRsum",  titleShort:"エコドライブ", level:"",  figNum:"21",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"アイドリングストップのほか、発進時にふんわりスタートすることにより、燃費を1割程度向上させることができます。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mCRtrain'] = { mid:"804",  name:"mCRtrain",  title:"鉄道やバスなど公共交通機関を利用する",  easyness:"2",  refCons:"consCRtrip",  titleShort:"公共交通", level:"",  figNum:"22",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"2km程度の近所の場合で、気候がいいときには、車を使わずに自転車を使ったり、歩いたりしましょう。健康のためにもなります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mCR20percent'] = { mid:"805",  name:"mCR20percent",  title:"車の利用を2割止める",  easyness:"1",  refCons:"consCRtrip",  titleShort:"車の利用2割減", level:"",  figNum:"22",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"車の利用は多くのエネルギーを消費します。必要性の薄い用途には使わないなどの工夫が大切です。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mCRwalk'] = { mid:"806",  name:"mCRwalk",  title:"近くの場合には車でなく、自転車や徒歩で行く",  easyness:"2",  refCons:"consCRtrip",  titleShort:"自転車や徒歩", level:"",  figNum:"22",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"2km程度の近所の場合で、気候がいいときには、車を使わずに自転車を使ったり、歩いたりしましょう。健康のためにもなります。",   lifestyle:"1",   season:"wss"};
	D6.scenario.defMeasures['mPTstopPlug'] = { mid:"901",  name:"mPTstopPlug",  title:"コンセントからプラグを抜き、待機電力を減らす",  easyness:"3",  refCons:"consTotal",  titleShort:"待機電力", level:"",  figNum:"20",  lifeTime:"",  price:"",  roanShow:"",  standardType:"",  subsidy :"",  advice:"テレビやビデオ、エアコンなど、使用していないときにも電気が消費されていることがあります。長時間使わないときには、コンセントからプラグを抜くことで削減ができます。最近の機種は待機電力が削減されており、5年以上前の機種で有効です。またエアコンは直接コンセントを抜くのではなく、まずリモコンでしっかり止めて、羽の動きが止まってから抜いてください。",   lifestyle:"1",   season:"wss"};


};

